[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nornir_scrapli"
dynamic = [
    "version",
]
description = "Scrapli's plugin for Nornir"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "nornir>=3.0.0",
    "nornir_utils>=0.1.0",
    "ntc_templates>=1.1.0",
    "scrapli>=2022.01.30",
    "scrapli_cfg>=2022.01.30",
    "scrapli_community>=2021.01.30",
    "scrapli_netconf>=2022.01.30",
    "textfsm>=1.1.0",
]
authors = [
    { name = "Carl Montanari", email = "carl.r.montanari@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = [
    "arista",
    "automation",
    "cisco",
    "eos",
    "iosxe",
    "iosxr",
    "juniper",
    "junos",
    "netconf",
    "network",
    "nxos",
    "ssh",
    "telnet",
]

[project.urls]
Homepage = "https://github.com/scrapli/nornir_scrapli"
Docs = "https://scrapli.github.io/nornir_scrapli/"

[project.entry-points."nornir.plugins.connections"]
scrapli = "nornir_scrapli.connection:ScrapliCore"
scrapli_cfg= "nornir_scrapli.connection:ScrapliConfig"
scrapli_netconf= "nornir_scrapli.connection:ScrapliNetconf"

[project.optional-dependencies]
dev = [
    "nornir_scrapli[genie]",
    "black>=23.3.0,<25.0.0", "darglint>=1.8.1,<2.0.0",
    "isort>=5.10.1,<6.0.0", "mypy>1.0.0,<2.0.0",
    "nox>=2025.2.9", "pydocstyle>=6.1.1,<7.0.0",
    "pylint>=3.0.0,<4.0.0", "pytest-cov>=3.0.0,<5.0.0",
    "pytest>=7.0.0,<8.0.0", "toml>=0.10.2,<1.0.0",
]
docs = [
    "mdx-gh-links>=0.2,<1.0", "mkdocs>=1.2.3,<2.0.0",
    "mkdocs-gen-files>=0.4.0,<1.0.0", "mkdocs-literate-nav>=0.5.0,<1.0.0",
    "mkdocs-material>=8.1.6,<10.0.0", "mkdocs-material-extensions>=1.0.3,<2.0.0",
    "mkdocs-section-index>=0.3.4,<1.0.0", "mkdocstrings[python]>=0.19.0,<1.0.0",
]
genie = [
    "genie>=20.2; sys_platform != 'win32' and python_version < '3.14'",
    "pyats>=20.2; sys_platform != 'win32' and python_version < '3.14'",
]

[dependency-groups]
dev = [{include-group = "nox"}, {include-group = "test"}, {include-group = "lint"}]
nox = ["nox>=2025.2.9"]
test = ["pytest>=7.0.0,<8.0.0", "pytest-cov>=3.0.0,<5.0.0"]
lint = [
    "black>=23.3.0,<25.0.0", "darglint>=1.8.1,<2.0.0",
    "isort>=5.10.1,<6.0.0", "mypy>1.0.0,<2.0.0",
    "pydocstyle>=6.1.1,<7.0.0", "pylint>=3.0.0,<4.0.0",
    "toml>=0.10.2,<1.0.0",
]
docs = ["nornir_scrapli[docs]"]
build = ["setuptools", "wheel"]

[tool.setuptools.dynamic]
version = { attr = "nornir_scrapli.__version__" }

[tool.setuptools.package-data]
nornir_scrapli = [
    "py.typed"
]

[tool.setuptools.packages.find]
include = ["nornir_scrapli*"]

[tool.coverage.run]
source = [
    "nornir_scrapli"
]

[tool.coverage.report]
sort = "cover"

[tool.coverage.paths]
source = [
    "nornir_scrapli",
    "*/site-packages/nornir_scrapli",
]

[tool.black]
line-length = 100
target-version = [
    "py310",
]

[tool.pydocstyle]
match-dir = "^nornir_scrapli/*"
ignore = "D101,D202,D203,D212,D400,D406,D407,D408,D409,D415"
# D101: missing docstring in public class
# D202: No blank lines allowed after function docstring
# D203: 1 blank line required before class docstring
# D212: Multi-line docstring summary should start at the first line
# D400: First line should end with a period
# D406: Section name should end with a newline
# D407: Missing dashed underline after section
# D408: Section underline should be in the line following the sections name
# D409: Section underline should match the length of its name
# D415: first line should end with a period, question mark, or exclamation point

[tool.isort]
skip_gitignore = true
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_first_party = "nornir"
known_third_party = "nornir_utils,pytest,scrapli,scrapli_netconf"

[tool.mypy]
python_version = "3.10"
pretty = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true
