name: Commit

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"
          python-version: "3.13"
          enable-cache: true
      - run: uv run --locked --only-group nox nox -s isort black pylint pydocstyle mypy darglint docs build

  unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"
          python-version: "3.13"
          enable-cache: true
      - run: uv python install ${{ matrix.python }}
      - run: uv run --locked --only-group nox nox -s unit_tests-${{ matrix.python }}
        env:
          TERM: xterm

  genie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.1"
          python-version: "3.13"
          enable-cache: true
      - run: uv run --locked --only-group nox nox -s genie
